# Cloudflare Workers 配置文件
name = "student-welfare-platform"
main = "worker.js"
compatibility_date = "2024-01-01"

# 静态资源配置
[[routes]]
pattern = "edu.869hr.uk/*"
zone_name = "edu.869hr.uk"

# 环境变量
[vars]
BUILD_VERSION = "1.0.0"
BUILD_DATE = "2025-10-24"

# 构建配置
[build]
command = "npm run build"
cwd = "."

# 兼容性标志
[compatibility_flags]
formdata_parser_supports_files = true
